#
# Makefile for the Lct tp driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_COMMON) += lct_tp.o
lct_tp-y := lct_tp_common.o lct_tp_gesture.o lct_tp_grip_area.o lct_tp_info.o \
			lct_tp_selftest.o lct_tp_work.o
